# Dockerfile for MySQL

# Use the official MySQL image from Docker Hub
FROM mysql:8.0

# Set environment variables for MySQL
ENV MYSQL_DATABASE=laravel_db
ENV MYSQL_ROOT_PASSWORD=1
ENV MYSQL_USER=laravel_user
ENV MYSQL_PASSWORD=1

# Expose port 3306
EXPOSE 3306
